# Generated by Django 3.2.16 on 2024-03-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrganiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='event_table',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event_table',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='event_table',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_app.eventcategory'),
        ),
        migrations.AddField(
            model_name='event_table',
            name='organiser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to='main_app.eventorganiser'),
        ),
    ]
