# Generated by Django 3.2.16 on 2024-03-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240321_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_table',
            name='category',
            field=models.ForeignKey(default='Party', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_app.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event_table',
            name='organiser',
            field=models.ForeignKey(default='Priyank', on_delete=django.db.models.deletion.CASCADE, related_name='organiser', to='main_app.eventorganiser'),
        ),
    ]
