# Generated by Django 3.2.16 on 2024-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20240321_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='cat_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
