# Generated by Django 3.2.16 on 2024-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_eventcategory_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganiser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
