# Generated by Django 5.0.3 on 2024-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_eventorganiser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_table',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
