# Generated by Django 5.0.3 on 2024-03-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_comments_event_table_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_table',
            name='comments',
        ),
        migrations.CreateModel(
            name='Eventcomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_table', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='main_app.event_table')),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
